services:
  l2_geth:
    image: l2_geth
    container_name: l2_geth
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    pull_policy: always
    volumes:
      - ./host:/host
      - ./data/taiko-geth:/data/taiko-geth
    ports:
      - "8545:8545"
      - "8546:8546"
      - "8551:8551"
    command:
      - --taiko
      - --gcmode
      - "archive"
      - --syncmode
      - "full"
      - --datadir
      - /data/taiko-geth
      - --networkid
      - "167200"
      - --metrics
      - --metrics.expensive
      - --metrics.addr
      - "0.0.0.0"
      - --http
      - --http.addr
      - "0.0.0.0"
      - --http.vhosts
      - "*"
      - --http.corsdomain
      - "*"
      - --http.port
      - "8545"
      - --ws
      - --ws.addr
      - "0.0.0.0"
      - --ws.origins
      - "*"
      - --ws.port
      - "8546"
      - --authrpc.addr
      - "0.0.0.0"
      - --authrpc.port
      - "8551"
      - --authrpc.vhosts
      - "*"
      - --authrpc.jwtsecret
      - /host/jwt.hex
      - --allow-insecure-unlock
      - --http.api
      - admin,debug,eth,net,web3,txpool,miner,taiko
      - --ws.api
      - admin,debug,eth,net,web3,txpool,miner,taiko
